[tool.pylint.messages_control]
disable = [
    "invalid-name",
    "line-too-long",
    "missing-module-docstring",
    "missing-timeout",
    "missing-class-docstring",
    "missing-function-docstring",
    "redundant-u-string-prefix",
    "unused-import",
    "import-error",
    "anomalous-backslash-in-string",
    "wrong-import-position",
    "redefined-outer-name",
    "not-context-manager",
    "too-many-locals",
    "unnecessary-lambda",
    "consider-using-f-string"
]

[tool.black]
line-length = 88
target-version = ['py39']
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
length_sort = true

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning"
]
